name: Testing
run-name: ${{ github.actor }} push in github some new
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: cmake -S . -B ${{github.workspace}}

      - name: Build
        # Build your program with the given configuration
        run:  cmake --build ${{github.workspace}} --target all -j 6

      - name: Testing
        run:  ctest --output-on-failure --extra-verbose

      - name: Result
        run: echo All work!!!