name: Testing
run-name: ${{ github.actor }} push in github some new
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        run: cmake -S . -B ${{github.workspace}}/cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake. --target all

      - name: Testing
        run:  ctest --test-dir ${{github.workspace}}/cmake --output-on-failure --extra-verbose

      - name: Result
        run: echo All work!!!